AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

  Exclude:
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
